# Welcome to Jekyll!
#

# Site settings
title: Inside360 - Professionelle 360 Grad Video Produktion
description: |
  Professional 360 degree \\
  panoramic video production
headline: Inside360
subline: |
  Immersive Film Making \\
  360-degree Virtual Reality \\
  conception and production
owner: Inside360 # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: whats@inside360.tv
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://inside360.tv" # the base hostname & protocol for your site
collections:
  projects:
    output: true
social:
  star-o: http://littlstar.com/inside360 #littlstar
  twitter: https://twitter.com/inside360tv
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/inside360tv
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:whats@inside360.tv
  #flickr:
  #instagram:
  youtube-square: https://www.youtube.com/channel/UC3S7FOKg-XSS1IO7_lyvvkA
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stumbleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  slack: http://inside360tv.slack.com
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
kramdown:
  input: GFM
#sass:
#  style: compressed

exclude: ['elements.html', 'generic.html']